FIX: Add placeholderRect override.
duongel/BetterTextField pull request #1
Opened 2017-06-07 10:56 UTC by Pitometsu

2017-06-07 11:51 UTC, duongel requested changes

2017-06-07 11:51 UTC, duongel commented on BetterTextField/BetterTextField.swift
> +    // Instets for the text position
Thanks for your contribution. Please fix typo `Insets` and add a colon at the end of the sentence.

2017-06-07 12:36 UTC, Pitometsu commented
Amended the typo.

2017-06-27 15:41 UTC, duongel approved these changes

2017-06-27 15:43 UTC, merged

2017-06-27 15:43 UTC, duongel commented
@Pitometsu so sorry for the delay, I was on vacation.